"""Remove jenis_mesin column

Revision ID: 4733fac4b37e
Revises: 8640951542df
Create Date: 2026-07-21 12:09:14.309477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4733fac4b37e'
down_revision = '8640951542df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('histories', schema=None) as batch_op:
        batch_op.drop_column('jenis_mesin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis_mesin', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
