"""Re-add specification columns

Revision ID: 8640951542df
Revises: c1c440e865d8
Create Date: 2026-07-21 12:05:49.324070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8640951542df'
down_revision = 'c1c440e865d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis_mesin', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('daya', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('jumlah_pole', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kecepatan_putaran_rpm', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('histories', schema=None) as batch_op:
        batch_op.drop_column('kecepatan_putaran_rpm')
        batch_op.drop_column('jumlah_pole')
        batch_op.drop_column('daya')
        batch_op.drop_column('jenis_mesin')

    # ### end Alembic commands ###
