"""Update history model schema

Revision ID: c1c440e865d8
Revises: 
Create Date: 2026-07-21 11:50:08.292799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1c440e865d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('indikasi_overheating', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('putaran_poros_seret', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('terminal_overheating', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cooling_duct_tersumbat', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('resistansi_isolasi_tidak_seimbang', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('resistansi_winding_tidak_seimbang', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('arus_antar_fasa_tidak_seimbang', sa.Boolean(), nullable=True))
        batch_op.drop_column('kecepatan_putaran_rpm')
        batch_op.drop_column('terminal_terbakar')
        batch_op.drop_column('bearing_aus_pecah')
        batch_op.drop_column('warna_gulungan_berubah')
        batch_op.drop_column('housing_bearing_aus')
        batch_op.drop_column('keretakan_dudukan')
        batch_op.drop_column('kebocoran_pelumas')
        batch_op.drop_column('jumlah_pole')
        batch_op.drop_column('resistansi_isolasi_normal')
        batch_op.drop_column('tegangan_stabil')
        batch_op.drop_column('lubang_spi_aus')
        batch_op.drop_column('sulit_start')
        batch_op.drop_column('jenis_mesin')
        batch_op.drop_column('daya')
        batch_op.drop_column('ampere_stabil')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ampere_stabil', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('daya', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('jenis_mesin', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('sulit_start', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lubang_spi_aus', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tegangan_stabil', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('resistansi_isolasi_normal', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('jumlah_pole', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kebocoran_pelumas', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('keretakan_dudukan', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('housing_bearing_aus', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('warna_gulungan_berubah', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bearing_aus_pecah', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('terminal_terbakar', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kecepatan_putaran_rpm', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('arus_antar_fasa_tidak_seimbang')
        batch_op.drop_column('resistansi_winding_tidak_seimbang')
        batch_op.drop_column('resistansi_isolasi_tidak_seimbang')
        batch_op.drop_column('cooling_duct_tersumbat')
        batch_op.drop_column('terminal_overheating')
        batch_op.drop_column('putaran_poros_seret')
        batch_op.drop_column('indikasi_overheating')

    # ### end Alembic commands ###
